environment:

  matrix:

    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.11"
      PYTHON_ARCH: "32"

    # - PYTHON: "C:\\Python27-x64"
    #  PYTHON_VERSION: "2.7.11" #
    #  PYTHON_ARCH: "64"

install:
  - set PATH=C:\Miniconda\Scripts
  - ps: If ($env:Platform -Match "x64") {$env:PATH="C:\Miniconda-x64\Scripts"}
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q --name python%PYTHON_VERSION% python=%PYTHON_VERSION%
  - activate python%PYTHON_VERSION%
  - pip install -i https://pypi.anaconda.org/carlkl/simple mingwpy
  - conda install -q --name python%PYTHON_VERSION% numpy matplotlib
  - python setup.py config --compiler=mingw32 --fcompiler=gfortran
  - python setup.py build --compiler=mingw32
  - python setup.py install

build: off

test_script:
  - python -c 'import sur'"

after_test:
  - python setup.py bdist_wheel"

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*

#on_success:
#  You can use this step to upload your artifacts to a public website.
#  See Appveyor's documentation for more details. Or you can simply
#  access your wheels from the Appveyor "artifacts" tab for your build.
